### ISSUE TITLE
Bad interpreter and bad encoding

### ISSUE THREAD

**Issue by hsanjuan** [cwjohan/markdown-to-html#2]
The interpreter is set to #!node when it should be to #!/usr/bin/env node

Additionally the npm-installed file for /usr/bin/markdown file is DOS encoded, which causes a "Wrong interpreter node^M" messages like: bash: /usr/bin/markdown: /usr/bin/node^M: bad interpreter: No such file or directory

**Comment by curcuz** [comment]
+1

**Comment by gka** [comment]
+1

you should use something like 

```
#!/usr/bin/env node
```

instead of 

```
#!node
```

**Comment by gka** [comment]
ah, no this seems to be a end-of-line character issue!

https://github.com/mllrsohn/node-webkit-builder/issues/75

**Comment by brownmike** [comment]
This comment on another issue solved the problem quite nicely for me https://github.com/nwjs/nw-builder/issues/75#issuecomment-55108563

Open the executables in VIM and use

    :set ff=unix

**Comment by cwjohan** [comment]
People suggesting solutions need to tell us what their environment is and
which environments they have tested to ensure the solution is portable.
There are people using just about every environment possible and we need a
solution that works in every environment. If it breaks some other
environment or breaks merges, we'll just get more bug reports.

But thanks, Mike, for the ": set ff=unix" workaround. That should work for
some people who have the problem and just want to get their script working.

**Comment by Karlheinzniebuhr** [comment]
+1 
I'm getting this on OS X Yosemite 10.10.5
<pre><code>
>markdown
>node^M: bad interpreter: No such file or directory
>markdown --help
>node^M: bad interpreter: No such file or directory
</code></pre>

**Comment by adrianhelvik** [comment]
+1
Getting it on OS X 10.9.5

    poopie:v2 Adde$ markdown readme.md 
    -bash: /usr/local/opt/nvm/versions/node/v4.0.0/bin/markdown: node^M: bad interpreter: No such file or directory

**Comment by MichaelJCole** [comment]
Same issue in Linux Mint.  Would be awesome if it did :-)

**Comment by MichaelJCole** [comment]
See also: https://github.com/pwlmaciejewski/markdown-html

**Comment by iambmelt** [comment]
+1 OS X Yosemite 10.10.5

**Comment by corsica** [comment]
+1, Linux

**Comment by jkatsnelson** [comment]
+1 OS X Yosemite 10.11.12

**Comment by gnujeremie** [comment]
+1 OS X El Capitan 10.11.3

**Comment by oimou** [comment]
+1 OS X El Capitan 10.11.2

**Comment by twitchard** [comment]
+1 archlinux

**Comment by dawnofthedev** [comment]
+1 Linux Mint 17.3 Cinnamon 64 bit

**Comment by louistsaitszho** [comment]
+1 OS X El Capitan 10.11 Beta (15A278b)

**Comment by rijnhard** [comment]
```
dos2unix script_name.js
```

done

**Comment by molomby** [comment]
+1 -- OS X El Capitan 10.11.5 (15F34)

**Comment by Obooman** [comment]
+1 OS X EL Capitan 10.11.6(15G31)

```bash
$ github-markdown index.md
$ zsh: /usr/local/bin/github-markdown: bad interpreter: node^M: no such file or directory
```

**Comment by smlombardi** [comment]
+1  also on 10.11.6 (15G1004)

```
-bash: /Users/stevelombardi/.nvm/versions/node/v6.4.0/bin/markdown: node^M: bad interpreter: No such file or directory
```

**Comment by cwjohan** [comment]
Can you not add /usr/bin/env to your path?

**Comment by jacksonrayhamilton** [comment]
+1 on Debian 8.5

There seems to be ample evidence that this problem will be fixed by accepting some of the open pull requests. I am pretty sure npm creates a wrapper batch script in windows that calls the program with `node`. Lots of bin scripts use `#!/usr/bin/env node` and work fine on Windows.

**Comment by cwjohan** [comment]
OK.  Done.  We now are using "#!/usr/bin/env node".

**Comment by cwjohan** [comment]
Accepted user critiques. We now are using "#!/usr/bin/env node".
