### ISSUE TITLE
Bad handling of special characters with markdownb

### ISSUE THREAD

**Issue by VictorLamoine** [cwjohan/markdown-to-html#28]
```
$ echo "Café" > test.md
$ cat test.md 
Café
$ markdown test.md 
<p>Café</p>
$ markdownb test.md 
View generated HTML in browser
```

The output of `markdown` is ok, but when using `markdownb` the generated HTML page contains:
```html
<p>CafÃ©</p>
```

**Comment by cwjohan** [comment]
UTF-8 encoding?  Should be supported.

**Comment by VictorLamoine** [comment]
Yes, utf-8:
```
$ echo "Café" > test.md
$ file -i test.md 
test.md: text/plain; charset=utf-8
```

Can you reproduce this bug?

**Comment by cwjohan** [comment]
No, sorry. I no longer have node.js runtime or dev environment. 

However, there may be a flag you set to indicate you want to use UTF-8.  Unfortunately, I can’t look at it right now and am travelling far from my computer.
